# Flaschen Taschen Hardware Configuration
# This file contains hardware-specific settings for the flaschen-taschen server

# Hardware display settings (used when --no-terminal is specified)
hardware:
  # GPIO mapping for LED matrix
  led_gpio_mapping: "adafruit-hat"
  
  # GPIO slowdown (helps with timing issues on some Pi models)
  led_slowdown_gpio: 2
  
  # LED brightness (0-100)
  led_brightness: 50
  
  # Display refresh rate settings
  led_show_refresh: true
  
  # Additional hardware options (uncomment and modify as needed)
  # led_scan_mode: 0
  # led_pwm_bits: 11
  # led_pwm_lsb_nanoseconds: 130
  # led_pwm_dither_bits: 0
  # led_limit_refresh: 0
  # led_inverse: false
  # led_rgb_sequence: "RGB"
  # led_pixel_mapper: ""
  # led_panel_type: ""

# Terminal display settings (used by default or with --terminal)
terminal:
  # Use high-definition terminal display
  hd_terminal: true

# General server settings
server:
  # Layer timeout in seconds (how long to keep a layer active without updates)
  layer_timeout: 15
  
  # Run as daemon (background process)
  daemon: false
